### ISSUE TITLE
Reproducing the results in the paper

### ISSUE THREAD

**Issue by linkct** [StanfordVL/alignment#1]
I recently read the paper preprint on Arxiv, and it's nice to have the official implementation here, thank you! I ran into some problems getting it up and running, for example when reproducing the ELIGN-adv result on Predator-Prey (2v2), the code gave an error in sacd_multi_wm.py, line 307, where nonzero_obs_count contains zeroes and yields NaN. The exact command I used is `python train_multi_sacd.py --task simple_tag_in --num-good-agents 2 --num-adversaries 2 --obs-radius 0.5 --intr-rew elign_adv --epoch 100 --save-models --benchmark  --logdir log/simple_tag_2_2_elign_adv_32procs --wandb-enabled --training-num 32 --test-num 32`. 
I'm also a little bit confused about the training time, which is 100+ epochs * 800K episodes per epoch * 25 timesteps per episode = 2*10^9+ timesteps in the Arxiv preprint; this seems somewhat large, could the authors confirm this? It would be great to have the scripts reproducing the main results, in case I made some mistakes regarding the command line arguments to use. Thank you!

**Comment by zixianma** [comment]
hi, thank you for the close reading! regarding the training time, I'm sorry about the confusion. It was a mistake in calculating the number of episodes per epoch. One epoch was in fact **4K episodes** of 25 timesteps in our experiments. I've submitted a new version of our paper to arxiv with this correction. Regarding the code error, I'll try to reproduce it and get back to you soon. Thanks!
