### ISSUE TITLE
Confused about the number of episodes and steps per episode while training

### ISSUE THREAD

**Issue by JunjunjunHJ** [StanfordVL/alignment#2]
Hello, I am so interested in your work about intrinsic reward. However, it makes me confused that the number of training episodes and steps per episode disagree with the code. Your paper said "800K episodes of 25 timesteps" for training and "1K test episodes" for evaluating. But the code set the "--epoch 10" and "--step-per-epoch 1000" by default. It bothers me again that the code setting trains even better. I don't know if something went wrong, just want to know the right episode and step per episode number.

Thanks.

**Comment by zixianma** [comment]
Hi, sorry about the confusion! As I noted in a previous issue too, there was a mistake in the writing, which I've corrected and updated on arxiv and in the latest version submitted to NeurIPS proceeding: One epoch was in fact **4K** episodes of 25 timesteps in our experiments. It's also worth noting that the default parameters are not necessarily the ones used in our experiments. Please follow the details in the paper and let me know if you have any questions! Thanks
